### PR TITLE
Add responsive css, update navbar on mobile and landing block

### LINKED ISSUE #46: Header & Footer, Make consistent to all pages.
Make sure all header/footers are the same as the format on front page.

### PR DESCRIPTION
**Pull request by mduw**
Changes in this push: adopt bootstrap 4.0.0 to all pages
- [x] unused styles remain in ``style.css`` (to be deleted). used styles + latests styles are in ``style2.css``.
- [x] update landing block (jumbotron) and navbar of all pages.
- [x] update footer of all pages. 
- [x] add "go up top" to all pages
- [x] add responsive components for mobile (all pages should be responsive at any screen size now) 
- [x] Apply container and grid system.

### CODE REVIEW

**Comment by redpandarevolt** [comment]
Mitchell those students.html pictures look so much better on all 3 device sizes, nice work.

### Changes for students.html page:
- [x] scroll up change to match the scroll up botton found on capstone & projects pages.
     ie. add space to the left of scroll up
          add box around finger
          make the same size of icon and font
- [x] Header change header to match the one on homepage sizing etc. (cut and paste it) 
- [x] Footer, same, make sure the footer is same as homepage so they are all consistent
 

Changes for events.html page:

- [x] header/footer cut and paste the one from home page onto events page so they are all consistent.
- [x] scroll button....see first checkbox above
- [x] Make sure major heading titles are aligned on the left with the paragraph blocks 
- [x] Paragraph Blocks: Put the title and date on the same line 
- [x] Calendar section: there may be a picture that is not showing up there, picture/word content should share the same left margin with all the headings and content blocks.
- [x] add media query smart phone devices to add padding on left and right, make headings fit better on small device ( check on chrome inspection tool for 425px) 


Once all the changes are made give another look on chrome inspection tool on 425px, 768px and large screen to double check everything. 


Question on style....Should we make all the headings and paragraphs the very dark purple color to match the dark purple in the picture??? I think it might me an easier transition on the eyes to have the same color.

**Comment by mduw** [comment]
> Mitchell those students.html pictures look so much better on all 3 device sizes, nice work.
> 
> ### Changes for students.html page:
> * [x]  scroll up change to match the scroll up botton found on capstone & projects pages.
>   ie. add space to the left of scroll up
>   add box around finger
>   make the same size of icon and font
> * [x]  Header change header to match the one on homepage sizing etc. (cut and paste it)
> * [x]  Footer, same, make sure the footer is same as homepage so they are all consistent
> 
> Changes for events.html page:
> 
> * [x]  header/footer cut and paste the one from home page onto events page so they are all consistent.
> * [x]  scroll button....see first checkbox above
> * [x]  Make sure major heading titles are aligned on the left with the paragraph blocks
> * [x]  Paragraph Blocks: Put the title and date on the same line
> * [x]  Calendar section: there may be a picture that is not showing up there, picture/word content should share the same left margin with all the headings and content blocks.
> * [x]  add media query smart phone devices to add padding on left and right, make headings fit better on small device ( check on chrome inspection tool for 425px)
> 
> Once all the changes are made give another look on chrome inspection tool on 425px, 768px and large screen to double check everything.
> 
> Question on style....Should we make all the headings and paragraphs the very dark purple color to match the dark purple in the picture??? I think it might me an easier transition on the eyes to have the same color.

@redpandarevolt all are updated based on your suggestion. pls check it again and let me know what you think

**Comment by mduw** [comment]
Screen Shot 2020-12-20 at 8 30 19 PM
Screen Shot 2020-12-20 at 8 29 59 PM
Screen Shot 2020-12-20 at 8 26 31 PM
Screen Shot 2020-12-20 at 8 25 46 PM
Screen Shot 2020-12-20 at 8 25 33 PM
Screen Shot 2020-12-20 at 8 25 14 PM
Screen Shot 2020-12-20 at 8 24 51 PM

**Comment by redpandarevolt** [comment]
Looks good, thank you so much for all your hard work Mitchell.

**Review by redpandarevolt — APPROVED** [review]
Looks good, time to merge.

**Pull request merged**
