### PR TITLE
Update media queries for students.html, remove T4G logo background, add effects to navbar

### PR DESCRIPTION
**Pull request by mduw**
👉  Following changes built on top of @redpandarevolt branch:
Students.html
- Update media queries for all screen.
- Add comments for code
index.html
-  remove T4G logo background
- add more effects on hover for items on navbar

### CODE REVIEW

**Comment by isabelgiang** [comment]
this seems like a complicated git workflow. 
is there a reason we can't merge one of our open PRs into master?

**Comment by mduw** [comment]
> this seems like a complicated git workflow.
> is there a reason we can't merge one of our open PRs into master?

agree! don't think there is any. @redpandarevolt do you want to merge your code into master?

**Comment by redpandarevolt** [comment]
> > this seems like a complicated git workflow.
> > is there a reason we can't merge one of our open PRs into master?
> 
> agree! don't think there is any. @redpandarevolt do you want to merge your code into master?

Yeah that sound fine.  It is my first time working with this set up so I was a tad reluctant to do any merging.  I will trust your good judgement.

**Comment by redpandarevolt** [comment]
Merging is blocked on my end..... that would be another reason I didn't take care of that.  Thank you so much for stepping in @hollowsunsets @mduw

**Comment by isabelgiang** [comment]
one moment, i will resolve the merge conflicts @mduw

**Comment by mduw** [comment]
> one moment, i will resolve the merge conflicts @mduw
@hollowsunsets  lmk if its easier to do it on my end

**Comment by mduw** [comment]
Nice! thanks @hollowsunsets

**Review by redpandarevolt — CHANGES_REQUESTED** [review]
Chrome Inspection at 425 Pixels shows all elements in Student card overlapping and jumbled.
- [x] Center and resize image in 425 media query
- [x] change size of ipsum lorem box to be center under image
- [x] center and shift location of contact information box to be under ipsum lorem box 
- [x] header at 425 size is not adjusting correctly 
- [x] footer at 425 size is not adjusting correctly 


- [x] Change Title in header to say T4G students

**Review by redpandarevolt — APPROVED** [review]
No merge conflicts on this branch. Going to merge onto main and continue working from there.

**Pull request merged**
